/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package prefuse.data.expression.parser;

public interface ExpressionParserConstants {

  int EOF = 0;
  int TRUE = 6;
  int FALSE = 7;
  int IF = 8;
  int THEN = 9;
  int ELSE = 10;
  int AND = 11;
  int OR = 12;
  int NOT = 13;
  int XOR = 14;
  int INT = 15;
  int DECIMAL_LITERAL = 16;
  int HEX_LITERAL = 17;
  int OCTAL_LITERAL = 18;
  int LONG = 19;
  int DOUBLE = 20;
  int FLOAT = 21;
  int EXPONENT = 22;
  int STRING = 23;
  int QUOTED = 24;
  int IDENTIFIER = 25;
  int LETTER = 26;
  int DIGIT = 27;
  int LPAREN = 28;
  int RPAREN = 29;
  int EQ = 30;
  int GT = 31;
  int LT = 32;
  int LE = 33;
  int GE = 34;
  int NE = 35;
  int ADD = 36;
  int SUB = 37;
  int MUL = 38;
  int DIV = 39;
  int POW = 40;
  int MOD = 41;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<TRUE>",
    "<FALSE>",
    "<IF>",
    "<THEN>",
    "<ELSE>",
    "<AND>",
    "<OR>",
    "<NOT>",
    "<XOR>",
    "<INT>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "<LONG>",
    "<DOUBLE>",
    "<FLOAT>",
    "<EXPONENT>",
    "<STRING>",
    "<QUOTED>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"<=\"",
    "\">=\"",
    "<NE>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
    "\"%\"",
    "\",\"",
  };

}
